### ISSUE TITLE
New group cover - july 2019

### ISSUE THREAD

**Issue by petk** [php-earth/group-cover#1]
Since the IWD 2019 is now over, we need something new... So, coming up :)

**Comment by cheddad2018** [comment]
![ppFFp](https://user-images.githubusercontent.com/33584599/61177303-dd638b80-a586-11e9-8007-a37f671ee609.png)

**Comment by okbach** [comment]
HHHHH THE FLAT EARTH
![ppp](https://user-images.githubusercontent.com/33584599/61177532-bd36cb00-a58c-11e9-9725-8163100374f1.png)

**Comment by petk** [comment]
New cover added - v2.16 https://github.com/phpearth/group-cover/releases/tag/v2.16

Thank you @cheddad2018 for your suggestion though! I really appreciate the effort :100:
